#!/usr/bin/env node

var program = require('commander');
var _ = require('./index')
program
  .version('0.0.1')
  .option('-a, --add', 'add two numbers')
  .option('-s, --sub', 'subtract two numbers')
  .parse(process.argv);

console.log('your anwser is:');
var num1 = parseInt(program.args[0]);
var num2 = parseInt(program.args[1]);
if (program.add) {
	var addSum = _.calc.add(parseInt(program.args[0]), parseInt(program.args[1]));
	console.log('the sum of ' + 
		parseInt(program.args[0]) + ' and ' + 
		parseInt(program.args[1]) + ' is ' + addSum);
};
if (program.sub){
	var subSub = _.calc.sub(num1, num2);
	console.log(num1 + ' - ' + num2 + ' equals ' + subSub);

};